spring.application.name=Job-Portal


spring.data.mongodb.database=jobPortal
test.message=HELLO_MONGODB
# MongoDB Configuration

#spring.data.mongodb.uri=mongodb+srv://dummygmail1212_db_user:g7UzsLUIHPbyqa85@jobportal.njv4pom.mongodb.net/?appName=jobPortal
#spring.data.mongodb.uri=mongodb+srv://dummygmail1212_db_user:g7UzsLUIHPbyqa85@jobportal.njv4pom.mongodb.net/jobPortal?retryWrites=true&w=majority



# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# SMTP Properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


USER_FOUND=User already register.
INVALID_CREDENTIALS=Invalid Credentials.
USER_NOT-FOUND=User not found.
OTP_INCORRECT=Incorrect OTP.
JOB_NOT_FOUND=Job not found.
JOB_APPLIED_ALREADY=Job applied already.
NO_NOTIFICATION_FOUND=No Notification Found.
TOKEN_IS_EXPIRED=Token Is Expired.
PROBLEM=Unable to get sequence id fo key.


#jwt cayteria
jwt.token.validity=21600
jwt.secret=yd10l/Wqe86E4xrtIrHGxpqVYQa1WuqOFbR/7ob7gxs2dfJ626Ve/7N8WgSOH7L9lg+fTOFbj+p3I4iXGbArog==



